// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8WYjskFdkFK9ujsBIARHbACCSGK9cl2o',
    appId: '1:393980898623:web:ab2da551bfdf112e03f78a',
    messagingSenderId: '393980898623',
    projectId: 'todoapp-526f8',
    authDomain: 'todoapp-526f8.firebaseapp.com',
    storageBucket: 'todoapp-526f8.appspot.com',
    measurementId: 'G-562LRJJ7LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjTNO65GjtwbEJ_eZHZC3x9uIrbjNoZ-s',
    appId: '1:393980898623:android:50727cc41dd4acf003f78a',
    messagingSenderId: '393980898623',
    projectId: 'todoapp-526f8',
    storageBucket: 'todoapp-526f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzBjya66IrsktWkhcJfVY_Zbpjc_e7g3Y',
    appId: '1:393980898623:ios:12ab411f92e7997f03f78a',
    messagingSenderId: '393980898623',
    projectId: 'todoapp-526f8',
    storageBucket: 'todoapp-526f8.appspot.com',
    iosBundleId: 'com.eraasoft.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzBjya66IrsktWkhcJfVY_Zbpjc_e7g3Y',
    appId: '1:393980898623:ios:f22719456e90f1b603f78a',
    messagingSenderId: '393980898623',
    projectId: 'todoapp-526f8',
    storageBucket: 'todoapp-526f8.appspot.com',
    iosBundleId: 'com.eraasoft.todoFirebase.RunnerTests',
  );
}
